# Generated by Django 3.2.8 on 2022-03-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
