# Generated by Django 3.2.8 on 2022-03-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='body',
        ),
    ]
