# Generated by Django 3.2.8 on 2022-03-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='complete',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
