# Generated by Django 3.2.8 on 2022-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='pac_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
