# Generated by Django 3.2.8 on 2022-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_tasks_pac_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='pac_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
